name: 'terraform-cloud-trigger-run'
description: 'Trigger Terraform Cloud run.'
inputs:
  tf-token:
    required: true
    description: 'An API token for Terraform Cloud.'
  workspace-name:
    required: true
    description: 'The Terraform Cloud workspace to update.'
  org-name:
    required: true
    description: 'The Terraform Cloud organization the workspace belongs to.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tf-token }}
    - ${{ inputs.workspace-name }}
    - ${{ inputs.org-name }}
